server:
  port: 8095

 
  application:
    name: REQUESTSERVICE
  sql:
    init:
      platform: postgres
  
spring:
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:postgresql://dbaas901.hyperp-dbaas.cloud.ibm.com:29411/mobicare
    username: mobisqluser
    password: mobicareCFC12!@#
    driver-class-name: org.postgresql.Driver
    
  jpa:
    show-sql: true
    open-in-view: false      
    hibernate:        
      ddl-auto: update      
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl                    
    properties:
      hibernate:        
        default_schema: public
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        jdbc:
          lob:
            non_contextual_creation: true
            
      
